### ISSUE TITLE
in-stock accuracy/RB aliases

### ISSUE THREAD

**Issue by tobioe** [atlefren/beerdatabase#6]
Looking very promising, good job. Two issues that may be obvious or in the works on but I'll mention anyway:

Such a db needs to be current to be relevant. Upon testing now, it would appear that the in-stock information of a given pol is dated to a stock snapshot from at least a month ago. Will olportalen be able to refresh the numbers to reflect the situation as the in-stock siutuation can change several times within a day?

Beers with Norwegian market alias names are not given the benefit of RB information, which is a shame since in most cases the AKA market name info is just one click away. Is it solveable to dig for the data that extra step?

**Comment by atlefren** [comment]
@tobioe Thanks for the feedback!

Regarding in-stock: I've set up a script to screen-scrape vinmonopolet.no for all beers in the database daily, but if you've found that the data is a month old there is possibly an error on my side. I will look into this. I think running the screen-scraping once a day should be sufficient, as from what I understand vinmonopolet.no is update once a day.

Regarding alias names: The Ratebeer-dump informs if a beer is an alis, but not what beer it's an alias of. I could add a "fix alias"-function to the page for alias beers, so that users could help me find the correct beer. Any other suggestions on how to solve this issue is appreciated!

**Comment by tobioe** [comment]
vinmonopolet.no is refreshed more than the once daily. Maybe I can get a more precise statement on this. 

The "month old" estimate is just a guess from the amount of now-unavailable christmas beer, seen when accessed by way of Polutsalg –> pol X

A user help alias fix seems sensible if there isn't a code way of making the connection. Sorry I can't (am truly unable to) be more helpful.

**Comment by atlefren** [comment]
@tobioe ok, then I'm wrong. Screen-scraping ~600 pages at vinmonopolet.no is a heavy operation, so for now I think I'll stick to daily, but we'll see. 

I'll look into the possible bug, see #9 

(Closing this issue, as I've moved stuff to separate issues)
